# PLEASE DO NOT REDISTRIBUTE !!!
# PLEASE GAIN ACCESS TO LATEST CODE DIRECTLY FROM AUTHOR (IN CASE ANY MODIFICATIONS WERE MADE)

# Author: Sean Parks (sean.parks@usda.gov)
# Date: 11.27.2023

# Note there have been some minor updates to the original code described in the paper.
# Updated by Jared Balik (jbalik@western.edu) to use terra package instead of raster package
# Thanks to Benjamin Gannon and Quinn Barber for coding improvements.

# This is just a sample to get you started. You will need to modify to suit your needs.
# There is probably a lot of legacy/useless code here, but it works!

# Rationale for this procedure, validation of results, and comparison to 
# other interpolation methods can be found in (please cite this paper if you use this code): 
# Parks. 2014. Mapping day-of-burning with coarse-resolution satellite fire-detection data. International Journal of Wildland Fire. 23:215-223.

# DOB = day of burning

# I recommend you check the outputs to make sure the code is running as expected.

# Please don't make fun of my poor coding.


##########################################################################################################
# This code is divided into three stages.
# 1. This stage selects those MODIS and VIIRS fire detection points that will be used to model day of burning
#	# Simply put, this stage selects all fire detections within 1km of a final fire perimeter and deletes duplicate fire detections
# 2. This stage models day of burning
# 3. This stage removes small (<= 25 ha) 'regions' that are generated by the interpolation in stage 2
###########################################################################################################



rm(list=ls(all=T))

pkgs <- c(
  "terra",
  "plyr",
  "dplyr",
  "tidyr",
  "stringr",
  "data.table",
  "rstudioapi", 
  "lubridate",
  "sf",
  "igraph",
  "timeDate", 
  "FNN"
)

# Install missing CRAN packages
missing_pkgs <- pkgs[!pkgs %in% installed.packages()[, "Package"]]
if (length(missing_pkgs) > 0) {
  install.packages(missing_pkgs)
}
# Load all packages
lapply(pkgs, library, character.only = TRUE)

# directories for data and scripts are defined in "user_input_general.csv"
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# read in user input
user_input_csv <- read.csv("user_input/user_input_general.csv", stringsAsFactors = FALSE)

# loop through user input csv and assign the values provided to the named objects
for (i in seq_len(nrow(user_input_csv))){
  val <- user_input_csv$value[i]
  if(user_input_csv$treat_as_R_expression[i] == T){val <- eval(parse(text = val))}
  assign(user_input_csv$name[i], val, envir = .GlobalEnv)
  rm(val)
}

# Navigate to whatever folder you're working
#5/29- weird bug right now where choose.dir() wont run until choose.files() is called
processed_data_directory <- file.path(choose.dir())
processed_data_directory <- gsub('\\\\', '/', processed_data_directory) #for windows
setwd(processed_data_directory)

########### You need 4 items to run this script, in their respective folders  #################
#these are all folders that need to be located within the processed_data_directory folder, change the folder name as needed
sub_folders <- c(
  firms = 'fire_detections/firms_fire_detections', #FIRMS data from https://firms.modaps.eosdis.nasa.gov/download
  perim = 'merged_perims', #fire perimeters of an area of interest, or all from https://mtbs.gov/direct-download
  fire_list = 'selectedfires', #List of fires of interest with an mtbs ID column
  fire_id_column = 'MTBS_ID', #name of the column that corresponds to the name/ID of the fire in the .csv of fires
  )



##### Set your processing parameters here #########
pixel_size = 30       #resolution, in meters
day_frac = 1          #fraction of day to divide FIRMS data, 0.5 = half day
round_type = floor    #options: round, floor, ceiling see ?round_any() for more info
shift_hour = 4        #number of hours to shift the hotspot timestamp, moves 3AM VIIRS pass to day prior
time_zone = 8 #7 for MST, need to figure out way to automate this (DST)
regions = 5 #the size of regions in hectares (and smaller to remove)
buffer = 1000 #size to buffer the fire perim by, 0 for no buffer
the_prj = CRS
selected_years = 'all years' #need to work on this
nifc_perims = F
date_format = 'yymmdd' # or 'julian'
output_directory = processed_data_directory


if (day_frac < 1) { #changes the raster type to float values (0.00..) if opting for sub daily
  data_type = 'FLT4S'
} else {
  data_type = 'FLT8S'
}


###
# Load hotspot data for all years and all of US
###

## Get MODIS fire detections
{
hotspotsModis = c(); hotspotsViirsSpp = c(); hotspotsViirsNoaa20 = c(); hotspotsViirsNoaa21 = c()
hotspotsModis <- st_read(list.files(file.path(global_data_directory,'fire_detections/firms_fire_detections', 'modis'), pattern = '.shp', full.names = T))
hotspotsModis <- subset(hotspotsModis, select = -c(TYPE))

## Get VIIRS fire detections
hotspotsViirsSpp <- st_read(paste0(global_data_directory, '/', sub_folders[['firms']], '/viirs'), 'fire_archive_SV-C2_431932')
hotspotsViirsSpp <- subset(hotspotsViirsSpp, select = -c(TYPE))
hotspotsViirsNoaa20 <- st_read(paste0(global_data_directory, '/', sub_folders[['firms']], '/viirs'), 'fire_nrt_J1V-C2_458502')
hotspotsViirsNoaa21 <- st_read(paste0(global_data_directory, '/', sub_folders[['firms']], '/viirs'), 'fire_nrt_J2V-C2_458503')

# Combine/clean/transfrom into one folder, 'hotspots'
hotspots <- rbind(hotspotsModis, hotspotsViirsSpp, hotspotsViirsNoaa20, hotspotsViirsNoaa21)
rm(hotspotsModis, hotspotsViirsSpp, hotspotsViirsNoaa20, hotspotsViirsNoaa21)
hotspots <- hotspots[, c('LATITUDE', 'LONGITUDE', 'ACQ_DATE', 'ACQ_TIME', 'SATELLITE', 'INSTRUMENT', 'FRP')]
hotspots <- st_transform(hotspots, crs = crs(the_prj))
hotspots$years <- lubridate::year(hotspots$ACQ_DATE) # Set column for year
}

###
# Import CSV of names and Ignition Dates
###

fires <- read.csv(file.path(processed_data_directory, 'fire_lists', 'selectedfires.csv'))
fires$year <- lubridate::year(fires$Ignition)
fires$yday <- lubridate::yday(fires$Ignition)
#fires <- fires |> filter(yday > 100) # Filter out fires that occurred before April 1st

years <- unique(fires$year) %>%
  sort()# Run all years 2001 - 20221

###
# Import MTBS fire perims
###




##
## Load function
##


#####################################################################################################################################################
#####################################################################################################################################################
# Stage 1 selects those fire detetections points that will be used to model day of burning (DOB) and write those points to a shapefile  #############
#																						                                                                                            #############
# NOTE THAT THIS CODE IS SPECIFIC TO FIRE DETECTION DATA OBTAINED FIRMS:										                                            #############
# https://firms.modaps.eosdis.nasa.gov/download/                                                               				                  #############
#																						                                                                                            #############
#####################################################################################################################################################
#####################################################################################################################################################
fire_hotspots <- function(year) {
  ## Load in the Fire List for the year of interest
  fire.list <- fires[fires$year == year,]
  
  # Subset Fire Hotspots for the year of interest
  hotspots <- subset(hotspots, years == year)
  
  
  for (xx in 1:dim(fire.list)[1]) {
    
    fire <- fire.list[[sub_folders[['fire_id_column']]]][xx]
    
    print(paste0('Starting on fire: ', fire, ' progress:', xx, '/', dim(fire.list)[1], ' year: ', year))
    

    fire.shp <- st_read(file.path(processed_data_directory, 'fire_perimeters', 'merged', paste0(fire, '_Extent.shp')))

    
    fire.shp <- st_transform(fire.shp, crs=the_prj)
    fire.shp.buffer.prj <- st_buffer(fire.shp, dist=2000)
    fire.shp.buffer.dd <- st_transform(fire.shp.buffer.prj, st_crs(fire.shp))
    
    # If there are clearly times when a fire should not be burning, those boundaries can be set here. Sometimes the fire detection
    # data picks up on industrial activities or slash pile burning or ???. The numbers correspond to Julian day.
    
    
    # This actually selects fire detections points relevant to the fire of interest
    
    fire.hotspots <- hotspots[fire.shp.buffer.dd,]
    
    
    if (nrow(fire.hotspots) > 0 ) {
      
      ## convert to local day/time based in time zone
      ## loc_JDT = local julian date with decimals (this is used for the interpolation)
      ## Changes time to Mountain Standard Time. Modify as appropriate.
      
      fire.hotspots$date <- as.numeric(yday(fire.hotspots$ACQ_DATE)) #convert acq_date to julian day
      fire.hotspots$time <- as.numeric(format(fire.hotspots$ACQ_TIME, digits=4))/2400 #convert acq_time to a decimal
      fire.hotspots$loc_JDT <- round(fire.hotspots$date + fire.hotspots$time - time_zone/24, 2) ## subtracting seven hours converts GMT to Mountain standard time
      
      ## One modification you might want to consider is 'shifting' the fire detections so that those detections that occur shortly after midnight 
      ## are assigned to the previous day. For example, you might want those fire detections from midnight and 4am to be assigned to the previous day. 
      ## You can make this adjustment where the change from GMT to local time is made by subtracting four hours, as shown below.
      ## Please note that I have no idea if this is a good idea, but the topic/idea has come up. 
      ## Also, this shift can be any window you want (e.g. 2 hrs, 6 hrs, or 9 hrs) and may be a better idea in forest vs. shrub/grass
      
      fire.hotspots$shift_JDT <- round(fire.hotspots$loc_JDT - shift_hour/24, 2) ## subtracting four hours to account for the 'shift' described above.
      #NOTE: 4/24=0.167, may not group some of the later NOAA20 into day prior if time zone is incorrect
      fire.hotspots$JDTround <- round_any(fire.hotspots$shift_JDT, day_frac, round_type) ## rounding by day frac
      
      min.date <- fire.list$yday[xx]-1 #day prior to ignition
      max.date <- fire.list$yday[xx]+120 #two months post-ignition
      
      
      # Again, if there are dates for specific fires that are invalid, they can be stated here. The numbers correspond to Julian day.
      
      # if (fire == 'MT4715311245620170723') {    
      # 	min.date <- 200; max.date <- 300 }
      
      
      ## If there are clearly invalid dates, use this.
      fire.hotspots <- subset(fire.hotspots, loc_JDT > min.date & loc_JDT < max.date)
      
      # Assigns and ID for accounting later
      
      fire.hotspots$ID <- seq(1, nrow(fire.hotspots))
      
      # This removes fire detections with the same location; they may be on the same date or different dates.
      # This selects the earlier date if there are more than fire detection with the same coordinate.
      # The coordinates function is also needed for finding the nearest neighbors each fire detection.
      
      modis.coords <- as.data.frame(st_coordinates(fire.hotspots))
      colnames(modis.coords) <- c('x','y')
      coord.df <- as.data.frame(modis.coords)
      coord.df$ID <- fire.hotspots$ID
      coord.df$DOB <- fire.hotspots$loc_JDT
      unique.coord.df <- unique(as.data.frame(modis.coords))
      
      for (rec in 1:nrow(unique.coord.df)) {
        subset <- subset(coord.df, x == unique.coord.df[rec,]$x & y == unique.coord.df[rec,]$y)
        if (nrow(subset) >= 2) {
          for (j in 2:nrow(subset)) {
            ID <- subset[j,]$ID
            fire.hotspots <- fire.hotspots[fire.hotspots$ID != ID,] 
          }
        }
      }
      fire.hotspots <- subset(fire.hotspots, select=c('ID', 'ACQ_DATE', 'ACQ_TIME', 'SATELLITE', 'FRP', 'date', 'time', 'loc_JDT', 'shift_JDT', 'JDTround'))
    }
      
      if(!dir.exists(paste0(output_directory, '/date_of_burn/'))){
        dir.create(paste0(output_directory, '/date_of_burn/'))
        }
      if(!dir.exists(paste0(output_directory, '/date_of_burn/hotspots'))){
        dir.create(paste0(output_directory, '/date_of_burn/hotspots'))
        }
      
      if(dim(fire.hotspots)[1] > 0){
        setwd(paste0(output_directory, '/date_of_burn/hotspots'))
        file.name <- paste(fire, '_', day_frac, '_hotspots.shp', sep='')
        st_write(fire.hotspots, file.name, delete_layer=TRUE)
        # plot(fire.hotspots[5]) ## plot using date field
      } else{
        
        print(paste0('No fire detection in ', fire.list$Name[xx]))
      }
    }
}


#####################################################################################
#####################################################################################
# Stage 2: this generates the preliminary modeled day of burning (DOB)  #############
#####################################################################################
dob_interpolation <- function(year) {
  ## Load in the Fire List for the year of interest
  fire.list <- fires[fires$year == year,]
  
  for (xx in 1:dim(fire.list)[1]) {
    
    fire <- fire.list[[sub_folders[['fire_id_column']]]][xx]
    
    print(paste0('Starting on fire: ', fire, ' progress:', xx, '/', dim(fire.list)[1], ' year: ', year))
    
    fire.shp <- st_read(file.path(processed_data_directory, 'fire_perimeters', 'merged', paste0(fire, '_Extent.shp')))
    
    
    if (nrow(fire.shp) > 0){
      
      fire.shp <- st_transform(fire.shp, crs=the_prj)
      fire.shp <- st_buffer(fire.shp, dist=buffer)
  
      # Get extent of fire perimeter of interest
      # Set number of row and columns for outputs
      (xmin <- (round((st_bbox(fire.shp)$xmin)/pixel_size) * pixel_size) - 15)
      (xmax <- (round((st_bbox(fire.shp))$xmax/pixel_size) * pixel_size) + 15)
      (ymin <- (round((st_bbox(fire.shp)$ymin)/pixel_size) * pixel_size) - 15)
      (ymax <- (round((st_bbox(fire.shp)$ymax)/pixel_size) * pixel_size) + 15)
      (nrow <- (ymax-ymin) / pixel_size)
      (ncol <- (xmax-xmin) / pixel_size)
      
      # Make blank raster and a fire perimeter raster
      blank.raster <- rast(nrows=nrow, ncols=ncol, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax)
      fire.perim.raster <- rasterize(fire.shp, blank.raster)
      
      
      ## Some perimeters may have zero fire detection, so a directory may not have been created in stage 1
      if (file.exists(paste0(output_directory, '/date_of_burn/hotspots/',fire, '_', day_frac, '_hotspots.shp'))) {
        
        # Get fire detection points
        setwd(paste0(output_directory, '/date_of_burn/hotspots/'))
        fire.hotspots <- st_read(paste(fire, '_', day_frac, '_hotspots.shp', sep=''), quiet = TRUE)
        fire.hotspots <- st_transform(fire.hotspots, crs=the_prj)
        
        # I am under the impression that one should not interpolate DOB if there are not very many fire detections
        if (nrow(fire.hotspots) >= 10) {
          
          fire.hotspots.truncated <-  as.data.frame(fire.hotspots)
          fire.hotspots.truncated <- fire.hotspots.truncated[,c('ID', 'JDTround')]
          fire.hotspots.truncated$new.id <- seq(1:nrow(fire.hotspots.truncated))
          
          unique.dates <- sort(unique(trunc(fire.hotspots$JDTround), decreasing=F))
          
          # Get xy coordinates for each pixel in area where DOB is to be estimated
          xy <- as.data.frame(xyFromCell(fire.perim.raster, 1:ncell(fire.perim.raster)))
          extracted <- terra::extract(fire.perim.raster, xy)
          extracted$layer[is.nan(extracted$layer)]<-NA
          xy <- cbind(xy,extracted)
          xy <- xy[,-c(3)]
          xy <- na.omit(xy)
          xy <- xy[,c(1,2)]
          
          # Get coordinates of fire detection points
          modis.coords <- as.data.frame(st_coordinates(fire.hotspots))
          colnames(modis.coords) <- c('x', 'y')
          
          # For each pixel, get five closest fire detection points
          nn5 <- get.knnx(cbind(modis.coords$x, modis.coords$y), xy, 5, algorithm='brute')
          IDs <- as.data.frame(nn5$nn.index)
          dists <- as.data.frame(nn5$nn.dist)
          unique <- as.data.frame(seq(1, nrow(xy)))
          
          # Makes data frame with columns of five nearest IDs, distances, and DOBs
          data <- cbind(unique, IDs)
          data <- cbind(data, dists)
          colnames(data) <- c('pixel.id', 'ID1', 'ID2', 'ID3', 'ID4', 'ID5', 'dist1', 'dist2', 'dist3', 'dist4', 'dist5')
          
          for (i in 1:5) {
            data$new.id <- data[,paste('ID',i,sep='')]
            data <- merge(data, fire.hotspots.truncated, by='new.id')
            data <- data[order(data$pixel.id),]
            assign(paste('DOB', i, sep=''), data$JDTround) 
            data <- data[,-c(13,14)]
          }
          
          data$DOB1 <- DOB1
          data$DOB2 <- DOB2
          data$DOB3 <- DOB3
          data$DOB4 <- DOB4
          data$DOB5 <- DOB5
          
          # Make column for the DOB estimates
          data$DOB.wmd <- 0 # weighted by mean and distance
          
          xyz <- as.data.frame(xy)
          colnames(xyz) <- c('x','y')
          
          #####################################################
          ### WEIGHTED MY MEAN and DISTANCE OF 5 NEAREST NEIGHBORS (WMD) (described in Parks [2014]).
          ### the average value of the five nearest fire detection points and it is 
          ### geographically closer to a fire detection point
          #####################################################
          
          # This assings weights to each of the five nearest neighbors
          data$DOB.tmp <- (apply(data[,c('DOB1', 'DOB2', 'DOB3', 'DOB4', 'DOB5')], 1, mean))
          
          data$wt1 <- 1/(((abs(data$DOB1 - data$DOB.tmp)+1) * data$dist1))
          data$wt2 <- 1/(((abs(data$DOB2 - data$DOB.tmp)+1) * data$dist2))
          data$wt3 <- 1/(((abs(data$DOB3 - data$DOB.tmp)+1) * data$dist3))
          data$wt4 <- 1/(((abs(data$DOB4 - data$DOB.tmp)+1) * data$dist4))
          data$wt5 <- 1/(((abs(data$DOB5 - data$DOB.tmp)+1) * data$dist5))
          data$wt <- data$wt1 + data$wt2 + data$wt3 + data$wt4 + data$wt5
          data$wt1 <- data$wt1/data$wt
          data$wt2 <- data$wt2/data$wt
          data$wt3 <- data$wt3/data$wt
          data$wt4 <- data$wt4/data$wt
          data$wt5 <- data$wt5/data$wt
          
          # This is the true WMD value
          data$DOB.tmp <-  round_any((
            (data$wt1 * data$DOB1) +
              (data$wt2 * data$DOB2) +
              (data$wt3 * data$DOB3) +
              (data$wt4 * data$DOB4) +
              (data$wt5 * data$DOB5)), day_frac, round) #could consider how 'round' type is affecting WMD
          
          # However, this code ensures that the estimated DOB will be a date of one of the five nearest values
          data.tmp <- data[,c('DOB1', 'DOB2', 'DOB3', 'DOB4', 'DOB5', 'DOB.tmp')]
          data.tmp$test <- apply(abs(data.tmp[,c('DOB1', 'DOB2', 'DOB3', 'DOB4', 'DOB5')] - data.tmp[,'DOB.tmp']), 1, which.min)
          data.tmp$test2 <- 0
          
          data.tmp$test2[which(data.tmp$test == 1)] <- data.tmp$DOB1[which(data.tmp$test == 1)]
          data.tmp$test2[which(data.tmp$test == 2)] <- data.tmp$DOB2[which(data.tmp$test == 2)]
          data.tmp$test2[which(data.tmp$test == 3)] <- data.tmp$DOB3[which(data.tmp$test == 3)]
          data.tmp$test2[which(data.tmp$test == 4)] <- data.tmp$DOB4[which(data.tmp$test == 4)]
          data.tmp$test2[which(data.tmp$test == 5)] <- data.tmp$DOB5[which(data.tmp$test == 5)]
          
          data$DOB.wmd <- data.tmp$test2
          
          
          
          # Create raster of modeled DOB
          xyz$z <- data[, 'DOB.wmd']
          #get year from year processing, convert julian date to yymmdd
          if (date_format == 'yymmdd') {
            year_date <- make_date(year, 1, 1)
            yymmdd <- as.numeric(format(make_date(year, 1, 1) + days(data$DOB.wmd-1), '%Y%m%d'))
            xyz$z <- (yymmdd-20000000)
          }
          
          if(!dir.exists(paste0(output_directory,'/date_of_burn/dob_tif'))){
            dir.create(paste0(output_directory,'/date_of_burn/dob_tif'))
          }
          
          setwd(paste0(output_directory,'/date_of_burn/dob_tif'))
          
          modeled.dob <- rast(xyz, type = 'xyz', crs=the_prj) 
          writeRaster(modeled.dob, paste0(fire,'_', day_frac, '_dob_tmp.tif'), datatype= data_type, overwrite=T)
          # plot(modeled.dob, 
          #   main = paste0(fire, '\nday of burning interpolation'),
          #   axes = FALSE)
        }
      }
    }
    else{
      print(paste0('No shapefile matching:', fire.list$Name[xx], 'moving to next...'))
    }
  gc()
  }
}


#####################################################################################
###################################################################################################################
###################################################################################################################
# Stage 3: This stage removes the 'small regions' (those that are less than 25 ha) from the modeled DOB      ######
# This only improves the overall prediction a little bit, but it is WAY more visually appealing              ######
###################################################################################################################
###################################################################################################################
raster_smoothing <- function(year) {
  
  ## Load in the Fire List for the year of interest
  fire.list <- fires[fires$year == year,]
  
  for (xx in 1:dim(fire.list)[1]) {
    
    fire <- fire.list[[sub_folders[['fire_id_column']]]][xx]
    
    print(paste0('Starting on fire: ', fire, ' progress:', xx, '/', dim(fire.list)[1], ' year: ', year))
  
    ## This is a check because stage 1 and 2 does not produce files if there are not enough fire detections
    if (file.exists(paste0(output_directory,'/date_of_burn/dob_tif/', fire,'_', day_frac, '_dob_tmp.tif'))) {
      
      # Load up the modeled DOB
      
      modeled.dob.raster <- rast(paste0(output_directory,'/date_of_burn/dob_tif/', fire,'_', day_frac, '_dob_tmp.tif'))	
      
      # Basically, these next steps create 'regions' for all continuous DOB estimates that are less than 25 ha
      # The value below, 278, should be modified to account for the cell size you are using
      # and if you want a different threshold than 25 ha.
      # This step takes a long time and could use someone with good coding skills to speed it up.
      
      size.factor = as.integer(regions*10000/(pixel_size^2))
      
      u <- unique(modeled.dob.raster)$z #u <- as.integer(u$z) 
      the.list <- list()
      
      for(j in 1:length(u)){
        x <- modeled.dob.raster==u[j]
        x <- 1*x # multiply by 1 to convert true/false matrix back to numeric (binary 0 and 1)
        patch.raster <- patches(x,directions=8, zeroAsNA=TRUE)
        rg.df <- na.omit(subset(as.data.frame(freq(patch.raster)),count > 0))
        rg.df$from <- rg.df$value - 0.25
        rg.df$to <- rg.df$value + 0.25
        rg.df$becomes <- 1
        rg.df$becomes[which(rg.df$count <= size.factor)] <- 99 
        rg.df$becomes[which(rg.df$count > size.factor)] <- 1
        rg.df <- as.matrix(rg.df[,c(4:6)]) 
        the.list[[j]] <- classify(patch.raster,rg.df)
      }
      the.stack <- sprc(the.list) 
      small.regions <- merge(the.stack)
      
      ##########################################################################################
      # Now, a nearest neighbor assignment is given to all pixels that have regions < 25 ha    #
      # from the nearest pixel that is part of a region > 25 hs.                               #
      ##########################################################################################
      
      xy <- as.data.frame(xyFromCell(small.regions, 1:ncell(small.regions)))
      nrow(xy)
      
      extracted <- terra::extract(small.regions$patches, xy) 
      extracted$patches[is.nan(extracted$patches)]<-NA
      xy <- cbind(xy,extracted)
      xy <- xy[,-c(3)]
      xy <- na.omit(xy)
      
      DOB <- terra::extract(modeled.dob.raster, xy[,c(1,2)])
      DOB <-DOB[,-c(1)]
      xy <- cbind(xy,DOB)
      xy$ID <- row.names(xy)
      
      nibble.df <- subset(xy, patches == 99)
      nibble.df <- nibble.df[,-c(3,4)]
      dob.df <- subset(xy, patches != 99)
      
      dob.df$ID <- seq(1, nrow(dob.df))
      dob.df.tmp <- dob.df[,-c(1,2,3)]
      dob.df.tmp$id.tmp <- dob.df.tmp$ID
      
      nibble.nn <- get.knnx(dob.df[,c(1,2)], cbind(nibble.df$x, nibble.df$y), 1, algorithm='brute')
      nibble.df$id.tmp <- nibble.nn$nn.index
      
      dob.df.tmp <- dob.df.tmp[,-c(2)]
      
      nibble.df <- merge(nibble.df, dob.df.tmp, by='id.tmp', all.x=T)
      nibble.df <- nibble.df[,-c(1,4)]
      
      dob.df <- rbind(dob.df[,c(1,2,4)], nibble.df)
      
      # This is the final DOB estimate	
      modeled.dob <- rast(dob.df, type = 'xyz', crs=(the_prj))
      
      setwd(paste0(output_directory,'/date_of_burn/dob_tif'))
      writeRaster(modeled.dob, paste0(fire,'_', day_frac, '_dob.tif'), datatype= data_type, overwrite=T)
      plot(modeled.dob,
           main = paste0(fire, '\nday of burning interpolation\nsmall regions <25ha removed'),
           axes = FALSE)
      #		file.remove('dob.tmp.tif'); file.remove('dob.tmp.tfw')
    }
  }
}

###############################################################
#################### RUNNING DOB FUNCTIONS ####################
###############################################################

{# Make a shapefile of satellite hotspots
system.time(lapply(years, fire_hotspots))

# Use each shapefile to interpolate raster of day of burn
system.time(lapply(years, dob_interpolation))

# Run raster smoothing function
system.time(lapply(years, raster_smoothing))}





  
# Remove temporary files for date of burn
#temp_dob <- dir(path = paste0(output_directory,'/date_of_burn/dob_tif'), pattern = 'tmp.tif')
#file.remove( paste0(output_directory,'/date_of_burn/dob_tif/', temp_dob))


################### Aggregate all DOB rasters by year #######################

# List all dob fires 
setwd(paste0(processed_data_directory, '/data/interim_data/date_of_burn/dob_tif'))
if (nifc_perims == T) {
  dob_files <- list.files(pattern = paste0('}_', day_frac, '_dob.tif$'))
} else {
  dob_files <-  list.files(pattern = paste0('^[^}]*_', day_frac, '_dob.tif$'))
}



# instead of julian day make date in format yyMMDD
#LEO: my suggestion would be to re-write all code to retain the yy/mm attribute in DOB per fire as julian date
add_yymmdd <- function(x){
  
  # download fire ID
  fire <- gsub(paste0('_', day_frac, '_dob.tif'),'', x)
  
  # Fire burn year
  year <- fires[fires[[sub_folders[['fire_id_column']]]] %in% fire,]$year
  
  dob <- terra::rast(paste0(output_directory,'/date_of_burn/dob_tif/', x))
  
  # Add year
  origin_year <- as.Date(paste0(year, '-01-01'))
  
  
  # Function to convert Julian Days to YYMMDD
  julian_day_to_yymmdd <- function(juliandays){
    #hack for leap year
    if(year %in% seq(2000,2032, 4)){
      print("accounting for leap year")
      date_obj <- origin_year + as.integer(juliandays)
    }else(date_obj <- origin_year + as.integer(juliandays) - 1)
    
    ##date_obj <- as.Date(juliandays, origin = origin_year)
    formatted_date <- format(date_obj, '%Y%m%d')
    return(formatted_date)
  }
  
  # as DF
  dob_df <- as.data.frame(dob, xy = T)
  
  # Run function to add year
  DOB <- julian_day_to_yymmdd(dob_df$DOB) |> as.numeric()
  
  # Range of days 
  # days <- na.omit(DOB)%% 100
  # range_days <- range(days)
  # print(range_days)

  #add coords and DOB
  dob_df$DOB <- DOB

  # Create a Raster
  modeled.dob.year <- rast(dob_df, type = 'xyz', crs=(the_prj))
  #writeRaster(modeled.dob.year, "Test.tif", overwrite = T, datatype = 'INT4U')
  
  return(modeled.dob.year)
}

# Function that creates a raster stack per year with formated date
stack_per_year <- function(y){
  print(paste0("year: ", y))
  IDs <- fires[fires$year == y,][[sub_folders[['fire_id_column']]]]
  
  dob_files_year <- dob_files[gsub(paste0('_', day_frac, '_dob.tif'),'', dob_files) %in% IDs]
  
  if (length(dob_files_year) > 0) {
    # Apply Function to all rasters
    if (date_format == "julian") {
      print("    converting to yyyymmdd")
      dob_stack <- lapply(dob_files_year, add_yymmdd)
    } else {
      dob_stack <- lapply(dob_files_year, rast)
    }
  
    #large_rast <- do.call(terra::mosaic, args = c(dob_stack, fun="modal"))
    # Combine into one large raster for the year
    if(length(dob_stack) > 1){
      # large_rast <- do.call(merge, dob_stack)
      large_sprc <- sprc(dob_stack)
      # CAUTION having trouble with merge rounding dates to even values, may be a RAM issue (restart R with clean env)
      large_rast <- terra::merge(large_sprc)
      #large_rast <- terra::mosaic(large_sprc, fun="min")
    } else {
      large_rast <- dob_stack[[1]]
    }
    
  
    #large_rast <- app(large_rast, function(x){x*10^6})
    if(!dir.exists(paste0(output_directory,'/date_of_burn/dob_by_years'))){
      dir.create(paste0(output_directory,'/date_of_burn/dob_by_years'))
    }
  
    # Write raster for year
    # Must save a 4-byte integer to preserve data values
  
    writeRaster(large_rast, paste0(output_directory,'/date_of_burn/dob_by_years/', sub_folders[[2]], '_', day_frac, '_dob_', y,'.tif'),  datatype = data_type, overwrite = T)

  }
  else{
    print(paste0('no fires for ', y))
  }
}

lapply(years, stack_per_year)



#